config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "feelings#index"
  # resources :feelings, only: :show
  namespace :films do
    resources :searches, only: :index
  end
  resources :films do
    resources :reviews do
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :review
  belongs_to :user
end

app/models/feeling.rb
class Feeling < ApplicationRecord

  has_many :reviews
  has_many :films
  # has_many :films, through: :film_feelings
end

app/models/film.rb
class Film < ApplicationRecord
  validates :title, :text, :image, presence: true
  has_many :reviews
  belongs_to :user, optional: true
  belongs_to :feeling, optional: true

  def self.search(search)
    return Film.all unless search
    Film.where('title LIKE(?)', "%#{search}%")
  end

  def getMaxfeeling
    @love = self.reviews.where(feeling_id: 1).count
    @laugh = self.reviews.where(feeling_id: 2).count
    @impressed = self.reviews.where(feeling_id: 3).count
    @fear = self.reviews.where(feeling_id: 4).count
    @courage = self.reviews.where(feeling_id: 5).count
    @adventure = self.reviews.where(feeling_id: 6).count

    feelings = {
      '1':  @love,
      '2':  @laugh,
      '3':  @impressed,
      '4':  @fear,
      '5':  @courage,
      '6':  @adventure
    }

    max_key = ""
    max_value = 0
    feelings.each {|key,value|
      if max_value < value
         max_key = key
         max_value = value
      end
    }
    return max_key.to_s.to_i
  end
end

app/models/film_feeling.rb
class FilmFeeling < ApplicationRecord
  belongs_to :film
  belongs_to :feeling
end

app/models/review.rb
class Review < ApplicationRecord
  validates :text, :feeling_id, presence: true
  belongs_to :user
  belongs_to :film
  has_many :comments
  belongs_to :feeling
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :films
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path # ログアウト後に遷移するpathを設定
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @film = Film.find(params[:film_id])
    @reviews = @film.reviews
    @review = Review.find(params[:review_id])
    @comment = Comment.new
    @comments = @review.comments
  end

  def create
    @review = Review.find(params[:review_id])
    Comment.create(comment_params)
    redirect_to film_review_comments_path
  end

  def edit
    @film = Film.find(params[:film_id])
    @review = Review.find(params[:id])
  end

private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, review_id: @review.id)
  end

end

app/controllers/feelings_controller.rb
class FeelingsController < ApplicationController
end

app/controllers/films/searches_controller.rb
class Films::SearchesController < ApplicationController
  def index
    @films = Film.search(params[:keyword])
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    # @films = Film.all
    id = params[:feeling_id]
    # @films = Film.where(feeling_id:id)
    # @jfilms = Film.where(text: "邦画")
    # @wfilms = Film.where(text:"洋画")
    # return @films = Film.all unless id
    # @j_films = @films.where(text:"邦画")
    # @w_films = @films.where(text:"洋画")
    if id == nil
      @j_films = Film.where(text: "邦画")
      @w_films = Film.where(text:"洋画")
    else
      @films = Feeling.find(id).films
      @j_films = @films.where(text:"邦画")
      @w_films = @films.where(text:"洋画")
    end
  end

  def new
    @film = Film.new
  end

  def create
    Film.create(film_params)
    redirect_to root_path
  end

  def show
    @film = Film.find(params[:id])
    @reviews = @film.reviews
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
  private
  def film_params
    params.require(:film).permit(:text,:title,:image).merge(user_id: current_user.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
    @A = Review.pluck(:film_id).group_by(&:itself).keys
    @data = []
    @A.each do |a|
      @B = Review.where(film_id: a).pluck(:feeling_id).group_by(&:itself).values
      @B.each do |b|
        @data << b.count
        return @data
      end
    end
  end

  def new
    @film = Film.find(params[:film_id])
    @review = Review.new
  end

  def create
    @review = Review.create(review_params)
    @film = Film.find(params[:film_id])
    film = Film.find_by(id: params[:film_id])
    id = film.getMaxfeeling
    film.update(feeling_id: id)
    redirect_to film_path(@film)
  end

  def destroy
    @film = Film.find(params[:film_id])
    review = Review.find(params[:id])
    review.destroy
    redirect_to film_path(@film)
  end

  def edit
    @film = Film.find(params[:film_id])
    @review = Review.find(params[:id])
  end

  def update
    @film = Film.find(params[:film_id])
    review = Review.find(params[:id])
    review.update(review_params)
    redirect_to film_path(@film)
  end

  private
  def review_params
    params.require(:review).permit(:text, :feeling_id, :film_id).merge(user_id: current_user.id)
  end

  def feeling_count
    @A = Review.pluck(:film_id)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films/searches_helper.rb
module Films::SearchesHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.haml
= render 'shared/header'

.wrapper-show
  .side_left
    .films__poster
      .films__poster__title
        %img.films__poster__title{src:@film.image}
      %h.films__poster__title

    .review
      %h2 Review List(各リストをクリックすると右画面でコメントできます)
      - @reviews.each do |r|
        %ul
          %li
            %time
              = r.created_at
            %name
              = r.user.name
            %text
              = link_to "/films/#{@film.id}/reviews/#{r.id}/comments" do
                = r.text

  .side_right
    .review-comment
      .review-comment__left
        .review-comment__left__name
          ="名前:#{@review.user.name}"
        .review-comment__left__contents__kind
          ="感情:#{@review.feeling.kind}"
        .review-comment__left__contents
          .review-comment__left__contents__text
            = @review.text
          -# .review-comment__left__contents__kind
          -#   ="感情:#{@review.feeling.kind}"
      .review-comment__right
        .review-comment__right__edit
        - if user_signed_in? && current_user.id == @review.user_id
          = button_to "編集する",edit_film_review_path(@film, @review), method: :get, class: 'review-comment__right__edit__review'
        .review-comment__right__destroy
        - if user_signed_in? && current_user.id == @review.user_id
          = button_to "削除する",film_review_path(@film,@review), method: :delete, class: 'review-comment__right__destroy__review'
    .comment-wrapper
      %p.comment-summary コメント一覧
      .comment-content
        - @comments.each do |comment|
          .comment-content__list
            .comment-content__list__text
              = simple_format comment.text
            .comment-content__list__info
              %span
                = comment.user.name
              %span
                -# = comment.review.created_at.strftime(“%Y-%m-%d %H:%M”)
      - if current_user
        .comment-form
          = form_for [@film, @review, @comment] do |f|
            = f.text_area :text, class: "comment-form__text", placeholder: "コメントを入力してください"
            = f.submit Comment, class: "comment-form__btn form_submit"

app/views/feelings/index.html.haml
= render 'shared/header'


%section.greeting
  .container
    .animate-title.inview
      %span.char F
      %span.char i
      %span.char l
      %span.char p
      %span.char p
      %span.char y

%section.feel
  %h2 Feeling
  %ul
    %li
      %a{:href => "/films?feeling_id=1"}
        %figure
          %img{:src => "https://cdn.pixabay.com/photo/2017/05/25/12/50/young-couple-2343265__480.jpg"}/
        %h3.feel
          恋したい
    %li
      %a{:href => "/films?feeling_id=2"}
        %figure
          %img{:src => "https://cdn.pixabay.com/photo/2015/10/16/17/15/person-991506__480.jpg"}/
        %h3 笑いたい
    %li
      %a{:href => "/films?feeling_id=3"}
        %figure
          %img{:src => "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTiu_9zDT4dxAax20o0gEiMy8IF-mdO0LTlK40zrFshQM5I4g9Y"}/
        %h3 感動したい
  %ul
    %li
      %a{:href => "/films?feeling_id=4"}
        %figure
          %img{:src => "https://cdn.pixabay.com/photo/2017/08/04/18/51/horror-2581018__480.jpg"}/
        %h3.feel
          恐怖を感じたい
    %li
      %a{:href => "/films?feeling_id=5"}
        %figure
          %img{:src => "https://cdn.pixabay.com/photo/2016/08/02/16/40/rage-1564031__480.jpg"}/
        %h3 勇気をもらいたい
    %li
      %a{:href => "/films?feeling_id=6"}
        %figure
          %img{:src => "https://cdn.pixabay.com/photo/2016/01/19/17/45/hiker-1149877__480.jpg"}/
        %h3 冒険したい
.copylight
  %p ©️ 2020 ohba

app/views/films/index.html.haml
= render 'shared/header'

.films-wrapper
  .films-header
    = form_with(url: films_searches_path, local: true, method: :get, class: "search-form") do |form|
      = form.text_field :keyword, placeholder: "映画を検索する", class: "search-input"
      = form.submit "検索", class: "search-btn"
  .japanese
    .japanese__films
      %h1.japanese__films__write
        邦画
        .japanese__films__poster
          - @j_films.each do |film|
            %ul.japanese__films__poster__list
              %li.japanese__films__poster__list__image
                =link_to film_path(film), class: "image" do
                  = image_tag film.image
              %li.japanese__films__title
                = film.title

  .western
    .western__films
      %h1.western__films__write
        洋画
        .western__films__poster
          - @w_films.each do |film|
            %ul.western__films__poster__list
              %li.western__films__poster__list__image
                =link_to film_path(film), class: "image" do
                  = image_tag film.image
              %li.western__films__title
                = film.title

app/views/films/new.html.haml
.register
  .register__form
    %h.register__form__name ★新規映画の登録★
    = form_with model: @film, class: "form__register", local: true do |form|
      .form__register__row
        .form__register__row__form
          %input#register__western__film{:name => "film[text]", :type => "radio", :class => "form__register__row__form__radio", :value => "洋画"}/
          = form.label :洋画, class: "form__register__row__form__radio"
        .form__register__row__form
          %input#register__japanese__film{:name => "film[text]", :type => "radio", :class => "form__register__row__form__radio",:value => "邦画"}/
          = form.label :邦画, class: "form__register__row__form__radio"
        = form.text_area :title, placeholder: :映画タイトル, class: :form__register__row__text
        = form.text_area :image, placeholder: :映画img, class: :form__register__row__image
        = form.submit '登録する', class: :form__register__row__btn

app/views/films/searches/index.html.haml
= render 'shared/header'
.films-wrapper
  .films-header
    = form_with(url: films_searches_path, local: true, method: :get, class: "search-form") do |form|
      = form.text_field :keyword, placeholder: "映画を検索する", class: "search-input"
      = form.submit "検索", class: "search-btn"

  .japanese__films__poster
    - @films.each do |film|
      %ul.japanese__films__poster__list
        %li.japanese__films__poster__list__image
          =link_to film_path(film), class: "image" do
            = image_tag film.image
        %li.japanese__films__title
          = film.title

app/views/films/show.html.haml
= render 'shared/header'

.wrapper-show
  .side_left
    .films__show-header
      = button_to "レビューを投稿する",new_film_review_path(@film), method: :get, class: 'films__show-header__review-post'
      -# .films__show-header__edit
      -#   = link_to "編集する",edit_film_review_path(@film)
      -# .films__show-header__destroy
      -#   = link_to "削除する",film_review_path(@film)
    .films__poster
      .films__poster__title
        %img.films__poster__title{:src => @film.image}
      %h.films__poster__title

    .review
      %h2 Review List(各リストをクリックすると右画面でコメントできます)
      - @reviews.each do |r|
        %ul
          %li
            %time
              = r.created_at
            %name
              = r.user.name
            %text
              = link_to film_review_comments_path(@film, r) do
                = r.text

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LetsFilm
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/reviews/edit.html.haml
.content
  .content__title
    新規レビューの作成
  = form_with model: [@film ,@review], class: :form, local: true do |form|
    .form__title
      = "タイトル：#{@film.title}"
    = form.hidden_field :film_id, value: @film.id
    .form__review
      = form.select :feeling_id, Feeling.all.map{|f| [f.kind, f.id]}, class: :form_feeling
    -# = form.text_field :film_id, placeholder: @film.title, class: :form__title, value: @film.id
    = form.text_area :text, placeholder: :レビュー本文, class: :form__text
    = form.submit '編集する', class: :form__post_btn
    = link_to "戻る", film_path(@film.id), class: :form__back_btn

app/views/reviews/new.html.haml
.content
  .content__title
    ★新規レビューの作成★
  = form_with model: [@film ,@review], class: :form, local: true do |form|
    .form__title
      = "【映画タイトル：#{@film.title}】"
    = form.hidden_field :film_id, value: @film.id
    .form__review
      = form.select :feeling_id, Feeling.all.map{|f| [f.kind, f.id]}, class: :form_feeling
    -# = form.hidden_field :film_id, value: @film.id
    -# = form.text_field :film_id, value: @film.title, class: :form__title
    = form.text_area :text, placeholder: :レビュー本文, class: :form__text
    = form.submit '投稿する', class: :form__post_btn
    = link_to "戻る", film_path(@film.id), class: :form__back_btn

app/views/shared/_header.html.haml
.header
  .header__nav
    %h1 Filppy
    .header__nav__left
      %ul.header__nav__left__menu
        %li
          = link_to "Home",root_path
        %li
          = link_to "投稿映画一覧",films_path
        %li
          = link_to "映画投稿",new_film_path

        %li
          %a{:href => "#"}
    .header__nav__right
      %ul.header__nav__right__name
        %li
          %name
            = current_user.name
      = link_to "ログアウト",destroy_user_session_path, method: "delete"